export const itemName = '[data-test="inventory-item-name"]'
export const itemPrice = '[data-test="inventory-item-price"]'
export const checkoutBtn = '[data-test="checkout"]'
export const firsName = '#first-name'
export const lastName = '#last-name'
export const zipCode = '#postal-code'
export const continueBtn = '[data-test="continue"]'
export const finishBtn = '[data-test="finish"]'
export const backHomeBtn ='[data-test="back-to-products"]'
